/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"
#include "MainMenuModel.h"
#include "MainWindow.h"

//==============================================================================
class SampleApplication  : public JUCEApplication
{
public:
    //==============================================================================
    SampleApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String &)
    {
        // This method is where you should put your application's initialisation code..
		commandManager = new ApplicationCommandManager();
		menuModel = new MainMenuModel(commandManager);
        mainWindow = new MainWindow(commandManager, menuModel);
    }

    void shutdown()
    {
        // Add your application's shutdown code here..

        mainWindow = nullptr; // (deletes our window)
		menuModel = nullptr;
		commandManager = nullptr;
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String &)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

private:
	ScopedPointer<ApplicationCommandManager> commandManager;
	ScopedPointer<MainMenuModel> menuModel;
    ScopedPointer<MainWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (SampleApplication)
